### ISSUE TITLE
Feature request: 在西文模式下，西文字母的特殊符号

### ISSUE THREAD

**Issue by Iey4iej3** [rime/rime-prelude#14]
在西文模式（`ascii_mode` 似乎不“准确”）下，有时需要输入非英语字母，例如法语音符 é，德语字母 œ, ü, ö 以及其他常用的 ç, č, ł 等（这在涉及人名及术语中还是很常用的）。目前只能切换到中文模式然后输入 `/` 寻找特殊字符，（尤其在手机上操作）似乎比较麻烦。部分半角字符似乎可以迁入 `ascii_mode`。

**Comment by lotem** [comment]
叫做「西文模式」是不太準確。這就是ASCII模式，或稱「不轉換」的模式。
這是從PC IME的角度來說，直接輸入鍵盤上的字符，而不經過輸入法的轉換。
你所描述的用法類似於在兩種輸入方案之間切換，比如 https://github.com/biopolyhedron/rime-latin-international 和中文輸入方案。
手機上的情況不同，不需要轉換的字符可以由前端虛擬鍵盤那部分實現。

**Comment by Iey4iej3** [comment]
就是说类似 AOSP 键盘功能的长按提取带音符字母的功能应当在前端（例如 Android 上 trime）上实现？主要是切换输入法在手机上相对麻烦，需要按好几次。我在电脑上用 compose key 实现，基本上不需要类似功能。
