### ISSUE TITLE
symbols.yaml有私用區字符「」

### ISSUE THREAD

**Issue by szieziw** [rime/rime-prelude#9]
這箇字符只有蘋果用戶看得到，感覺放在rime默認配置文件中不合适

**Comment by eatradish** [comment]
只與字體有關吧，我在 Linux 上也能看到。

**Comment by szieziw** [comment]
> 只與字體有關吧，我在 Linux 上也能看到。

是的

在Unicode中，私人使用區（簡稱：私用區；英語：Private Use Areas，簡稱：PUA）指其解釋未在Unicode標準中指定，而是由合作用戶之間的私人協議決定其用途的一系列碼位。[4] 目前定義了三個私人使用區：一個在基本多語言平面（U+E000-U+F8FF）中，另外兩個幾乎包含了整個第15和第16平面（分別為U+F0000-U+FFFFD，U+100000-U+10FFFD）。[5]

私人使用區字符的分配，可不由字面意義上的私人決定；一些組織已經發布了一些分配計劃。但根據其定義，私人使用區相同的代碼點可被分配為不同的字符，因此用戶可能因安裝了某種字體，看到其顯示為一種形態，但使用了其他字體的用戶可能看到完全不同的字符。

        這箇碼位被蘋果用來放其logo，所以在蘋果的設備上看到的是蘋果logo，其它非蘋果用户除非字體裏這箇碼位和蘋果一樣放了它的logo，否則看到的可能是豆腐塊或其它的╮(╯_╰)╭

**Comment by lotem** [comment]
那確實不該收錄。

**Comment by lotem** [comment]
Fixed by https://github.com/rime/rime-prelude/commit/00a5b5a40b0e4419869ec3783744c75a8c86a5d7
